Systems-Kronos/kronos-spring-api-sql

- pom.xml
- src/main/java/com/kronosapisql/controller/EmpresaController.java
- src/main/java/com/kronosapisql/handler/GlobalExceptionHandler.java
- src/main/java/com/kronosapisql/model/Empresa.java
- src/main/java/com/kronosapisql/repository/EmpresaRepository.java
- src/main/java/com/kronosapisql/service/EmpresaController.java
- src/main/java/com/kronosapisql/service/EmpresaService.java
- src/main/resources/application.properties
- src/test/aaa.http
Metodos de atualizar, deletar, criar e ler as empresas
---
- [ x ] Código testado localmente
- [ x ] Nenhum erro no build
- [ x ] PR está seguindo a estrutura definida
- [    ] Revisado por pelo menos uma pessoa
---
https://trello.com/c/3AijelTb/4-ds2-criar-m%C3%A9todos-crud-da-entidade-empresa
---
> metodos de atualizar, deletar, criar e ler as empresas

- pom.xml
- src/main/java/com/kronosapisql/controller/EmpresaController.java
- src/main/java/com/kronosapisql/controller/SetorController.java
- src/main/java/com/kronosapisql/model/Setor.java
- src/main/resources/application.properties
documentacao do setor e empresa
---
- [ x ] Código testado localmente
- [ x ] Nenhum erro no build
- [ x ] PR está seguindo a estrutura definida
---
[Inclua links para tarefas relacionadas, issues ou qualquer detalhe relevante.]
https://trello.com/c/QwYnk9CT/6-ds2-criar-m%C3%A9todos-crud-da-entidade-setor
https://trello.com/c/3AijelTb/4-ds2-criar-m%C3%A9todos-crud-da-entidade-empresa
---
> documentacao do setor e empresa

- src/main/java/com/kronosapisql/controller/EmpresaController.java
- src/main/java/com/kronosapisql/controller/HabilidadeController.java
- src/main/java/com/kronosapisql/controller/MensagemController.java
- src/main/java/com/kronosapisql/controller/PlanoPagamentoController.java
- src/main/java/com/kronosapisql/controller/SetorController.java
- src/main/java/com/kronosapisql/controller/UsuarioController.java
- src/main/java/com/kronosapisql/handler/GlobalExceptionHandler.java
- src/main/java/com/kronosapisql/model/Empresa.java
- src/main/java/com/kronosapisql/model/Habilidade.java
- src/main/java/com/kronosapisql/model/Mensagem.java
- src/main/java/com/kronosapisql/model/PlanoPagamento.java
- src/main/java/com/kronosapisql/model/Setor.java
- src/main/java/com/kronosapisql/model/Usuario.java
- src/main/java/com/kronosapisql/repository/HabilidadeRepository.java
- src/main/java/com/kronosapisql/repository/MensagemRepository.java
- src/main/java/com/kronosapisql/repository/PlanoPagamentoRepository.java
- src/main/java/com/kronosapisql/repository/SetorRepository.java
- src/main/java/com/kronosapisql/service/EmpresaService.java
- src/main/java/com/kronosapisql/service/HabilidadeService.java
- src/main/java/com/kronosapisql/service/MensagemService.java
- src/main/java/com/kronosapisql/service/PlanoPagamentoService.java
- src/main/java/com/kronosapisql/service/SetorService.java
- src/main/java/com/kronosapisql/service/UsuarioService.java
Adicionando os métodos CRUD de Plano Pagamento
---
---
---
---
---
> feat: Adicionando os métodos CRUD de Plano Pagamento

- .github/pull_request_template.md
Arrumando pull request template
---
---
---
---
---
> docs: arrumando pull request template

- src/main/java/com/kronosapisql/model/PlanoVantagens.java
- src/main/java/com/kronosapisql/model/Usuario.java
- src/main/java/com/kronosapisql/repository/PlanoVantagensRepository.java
Mudei o relacionamento da entidade PlanoVantagens com a entidade PlanoPagamento, para @ManytoOne, tirando o tipo list desse atributo, transformando o em um objeto da entidade PlanoPagamento 
---
---
---
- Alguma parte crítica foi alterada? Não 
---
---
> Fix: Corrigindo o relacionamento da entidade PlanoVantagens

- src/main/java/com/kronosapisql/dto/LoginDTO.java
- src/main/java/com/kronosapisql/model/Empresa.java
- src/main/java/com/kronosapisql/model/Habilidade.java
- src/main/java/com/kronosapisql/model/Mensagem.java
- src/main/java/com/kronosapisql/model/PlanoPagamento.java
- src/main/java/com/kronosapisql/model/PlanoVantagens.java
- src/main/java/com/kronosapisql/model/Setor.java
- src/main/java/com/kronosapisql/model/Usuario.java
Adicionei o lombok em todas as classes Model
---
---
---
---
---
> feat: adicionando lombok em todas as classes model

- src/main/java/com/kronosapisql/controller/EmpresaController.java
- src/main/java/com/kronosapisql/controller/HabilidadeController.java
- src/main/java/com/kronosapisql/controller/MensagemController.java
- src/main/java/com/kronosapisql/controller/PlanoPagamentoController.java
- src/main/java/com/kronosapisql/controller/PlanoVantagensController.java
- src/main/java/com/kronosapisql/controller/SetorController.java
- src/main/java/com/kronosapisql/controller/UsuarioController.java
- src/main/java/com/kronosapisql/service/EmpresaService.java
Renomeando algumas rotas e corrigindo métodos
---
---
---
---
---
> fix: Renomeando algumas rotas e corrigindo métodos

- src/main/java/com/kronosapisql/controller/PlanoPagamentoController.java
- src/main/java/com/kronosapisql/controller/PlanoVantagensController.java
Coloquei a barra antes das rotas.
---
---
---
- Alguma parte crítica foi alterada?
- Pode afetar outras funcionalidades?
---
---
> Fix: Mantendo as rotas no padrão

- src/main/java/com/kronosapisql/controller/UsuarioController.java
- src/main/java/com/kronosapisql/dto/LoginDTO.java
Corrigindo o método de login, usando como credencial o CPF no lugar do email
---
---
---
---
---
> fix: Corrigindo o método de login

- src/main/java/com/kronosapisql/controller/ReportController.java
- src/main/java/com/kronosapisql/controller/TarefaController.java
- src/main/java/com/kronosapisql/model/Report.java
- src/main/java/com/kronosapisql/model/Tarefa.java
- src/main/java/com/kronosapisql/repository/ReportRepository.java
- src/main/java/com/kronosapisql/repository/TarefaRepository.java
- src/main/java/com/kronosapisql/service/ReportService.java
- src/main/java/com/kronosapisql/service/TarefaService.java
Adicionando as classes e métodos necessários para o crud da entidade Tarefa
---
---
---
---
---
> feat: Adicionando o crud da entidade Tarefa

- src/main/java/com/kronosapisql/controller/ReportController.java
- src/main/java/com/kronosapisql/dto/LoginDTO.java
- src/main/java/com/kronosapisql/model/Empresa.java
- src/main/java/com/kronosapisql/model/Mensagem.java
- src/main/java/com/kronosapisql/model/PlanoPagamento.java
- src/main/java/com/kronosapisql/model/Setor.java
- src/main/java/com/kronosapisql/model/Usuario.java
- src/main/java/com/kronosapisql/repository/PlanoVantagensRepository.java
- src/main/java/com/kronosapisql/repository/SetorRepository.java
- src/main/java/com/kronosapisql/security/JwtFilter.java
- src/main/java/com/kronosapisql/security/JwtUtil.java
- src/main/java/com/kronosapisql/security/SecurityConfig.java
- src/main/java/com/kronosapisql/service/ReportService.java
Correções no model de Usuario.
---
---
---
---
---
> fix: correções no model de Usuario

- pom.xml
- src/main/java/com/kronosapisql/repository/UsuarioRepository.java
- src/main/java/com/kronosapisql/security/JwtUtil.java
- src/main/java/com/kronosapisql/service/UsuarioService.java
- src/main/resources/application.properties
Aalterações no login e conexão com banco.
---
---
---
- Pode afetar outras funcionalidades? Sim
---
---
> fix: alterações no login e conexão com banco

- src/main/java/com/kronosapisql/controller/TarefaController.java
- src/main/java/com/kronosapisql/controller/UsuarioController.java
- src/main/java/com/kronosapisql/dto/TarefaHabilidadeDTO.java
- src/main/java/com/kronosapisql/dto/TarefaRequestDTO.java
- src/main/java/com/kronosapisql/dto/TarefaUsuarioDTO.java
- src/main/java/com/kronosapisql/handler/GlobalExceptionHandler.java
- src/main/java/com/kronosapisql/model/Tarefa.java
- src/main/java/com/kronosapisql/model/TarefaHabilidade.java
- src/main/java/com/kronosapisql/model/Usuario.java
- src/main/java/com/kronosapisql/repository/UsuarioRepository.java
- src/main/java/com/kronosapisql/service/TarefaService.java
- src/main/java/com/kronosapisql/service/UsuarioService.java
Relacionamento de Tarefa com as habilidades
---
---
---
- Alguma parte crítica foi alterada?
Não
- Pode afetar outras funcionalidades?
Não
---
https://trello.com/c/auKFKtPJ/9-ds2-criar-m%C3%A9todos-crud-da-entidade-tarefahabilidade-sql
---
> feat: tarefa habilidade

- src/main/java/com/kronosapisql/controller/HabilidadeUsuarioController.java
- src/main/java/com/kronosapisql/model/HabilidadeUsuario.java
- src/main/java/com/kronosapisql/repository/HabilidadeUsuarioRepository.java
- src/main/java/com/kronosapisql/service/HabilidadeUsuarioService.java
Adicionando os métodos e classes necessárias para o CRUD da entidade Habilidade Usuário 
---
---
---
- Alguma parte crítica foi alterada? Não 
- Pode afetar outras funcionalidades? Sim
---
---
> feat: Adicionando o crud da entidade Habilidade Usuário

- src/main/java/com/kronosapisql/controller/UsuarioController.java
- src/main/java/com/kronosapisql/service/UsuarioService.java
Adicionando método de selecionar o usuário pelo CPF
---
---
---
---
---
> feat: Adicionando método de selecionar o usuário pelo CPF

- src/main/java/com/kronosapisql/controller/TarefaController.java
- src/main/java/com/kronosapisql/dto/TarefaFunctionDTO.java
- src/main/java/com/kronosapisql/dto/TarefaUsuarioDTO.java
- src/main/java/com/kronosapisql/repository/TarefaRepository.java
- src/main/java/com/kronosapisql/service/TarefaService.java
Adicionei todas as classes e métodos necessários para o funcionamento da function de listar tarefas
---
---
---
---
---
> feat: Adicionando método de selecionar através da function

- src/main/java/com/kronosapisql/dto/TarefaRequestDTO.java
- src/main/java/com/kronosapisql/model/Tarefa.java
Alterando o nome da coluna nTempoEstimado pra iTempoEstimado e o tipo de Double pra Integer
---
---
---
---
---
> refactor: alterando o nome da coluna nTempoEstimado pra iTempoEstimado

- src/main/java/com/kronosapisql/security/CorsConfig.java
- src/main/java/com/kronosapisql/security/SecurityConfig.java
Ssecurity para permitir cors.
---
---
---
- Pode afetar outras funcionalidades? Sim
---
---
> fix: security para permitir cors

- src/main/java/com/kronosapisql/dto/ReportDTO.java
- src/main/java/com/kronosapisql/model/Report.java
- src/main/java/com/kronosapisql/repository/ReportRepository.java
- src/main/java/com/kronosapisql/service/ReportService.java
Corrigindo o método de inserir o report e reportDTO
---
---
---
---
---
> fix: Corrigindo o método de inserir o report e reportDTO

- src/main/java/com/kronosapisql/repository/LogAtribuicaoTarefaRepository.java
- src/main/java/com/kronosapisql/service/LogAtribuicaoTarefaService.java
Adicionando o findById no LogAtribuicaoTarefaRepository
---
---
---
---
---
> feat: adicionando no repository o metodo de findbyid

- src/main/java/com/kronosapisql/model/LogAtribuicaoTarefa.java
Consertando o model, indicando o schema correto na classe LogAtribuicaoTarefa
---
---
---
- Alguma parte crítica foi alterada?
- Pode afetar outras funcionalidades?
---
---
> fix: Consertando o model, indicando o schema correto

- src/main/java/com/kronosapisql/controller/LogAtribuicaoTarefaController.java
- src/main/java/com/kronosapisql/repository/LogAtribuicaoTarefaRepository.java
- src/main/java/com/kronosapisql/service/LogAtribuicaoTarefaService.java
Criando método para encontrar o log pelo ID do usuário atuante
---
---
---
---
---
> feat: Criando método para encontrar o log pelo id do usuario atuante

- src/main/java/com/kronosapisql/controller/ReportController.java
- src/main/java/com/kronosapisql/controller/TarefaController.java
- src/main/java/com/kronosapisql/repository/ReportRepository.java
- src/main/java/com/kronosapisql/repository/TarefaRepository.java
- src/main/java/com/kronosapisql/service/ReportService.java
Adicionando método para atualizar status de um report.
---
---
---
---
---
> feat: adicionando método para atualizar status de um report
